[phases.setup]
nixPkgs = ["python311", "gcc", "libffi", "openssl", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python neon_api_server.py"
